# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 19:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('value', models.CharField(max_length=70)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('creation_date',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'GPS', b'GPS'), (b'WIFI', b'WIFI'), (b'BLE', b'BLE')], default=b'GPS', max_length=4)),
                ('name', models.CharField(max_length=70)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('radius', models.FloatField(blank=True, null=True)),
                ('ssid', models.CharField(blank=True, max_length=70)),
            ],
            options={
                'ordering': ('creation_date',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=70)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('policy', models.CharField(choices=[(b'WL', b'White List'), (b'BL', b'Black List')], default=b'WL', max_length=2)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('centralized_mode', models.BooleanField()),
                ('content', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='locmess.Location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('creation_date',),
            },
        ),
        migrations.AddField(
            model_name='interest',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='interests', to='locmess.Post'),
        ),
        migrations.AddField(
            model_name='interest',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='interests', to=settings.AUTH_USER_MODEL),
        ),
    ]
